server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Team-Study-Bridge/config-repo
          username: yjincode
          password: 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
          clone-on-start: true
          force-pull: true
          default-label: main