apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.name }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
              name: http
          lifecycle:
            preStop:
              exec:
                command:
                  - sh
                  - -c
                  - sleep 5
          env:
            - name: CONFIG_GIT_URI
              valueFrom:
                secretKeyRef:
                  name: config-service-secrets
                  key: CONFIG_GIT_URI
            - name: CONFIG_GIT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: config-service-secrets
                  key: CONFIG_GIT_USERNAME
            - name: CONFIG_GIT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: config-service-secrets
                  key: CONFIG_GIT_PASSWORD