name: CD - Build, Push, Update Helm, PR

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-northeast-2
  ECR_REPOSITORY: aigungbu/service-images
  IMAGE_TAG: ${{ github.sha }}
  SERVICE_NAME: config-service
  HELM_PATH: helm/config-service/values.yaml

jobs:
  cd-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$AWS_REGION.amazonaws.com

      - name: Build and push Docker image
        run: |
          docker build -t $SERVICE_NAME:$IMAGE_TAG .
          docker tag $SERVICE_NAME:$IMAGE_TAG ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Update Helm values.yaml with image tag and Git credentials
        run: |
          yq eval "
            .image.tag = \"$IMAGE_TAG\" |
            .env[0].value = \"${{ secrets.CONFIG_GIT_URI }}\" |
            .env[1].value = \"${{ secrets.CONFIG_GIT_USERNAME }}\" |
            .env[2].value = \"${{ secrets.CONFIG_GIT_PASSWORD }}\"
          " -i $HELM_PATH

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "chore(config-service): update image tag to $IMAGE_TAG and git credentials"
          title: "chore(config-service): update image tag to $IMAGE_TAG"
          body: "Auto-generated PR to update Docker image tag and secrets"
          branch: update/config-service-image-${{ github.sha }}
          base: main
          delete-branch: true
